export const campaigns = [
    {
        name: 'Beach',
        image: '',
        Location: 'LA',
        description: 'Beach has been polluted by plastic. Come forward to clean this shit',
        members: 20,
        donation: 2000,
    },
    {
        name: 'Beach',
        image: '',
        Location: 'LA',
        description: 'Beach has been polluted by plastic. Come forward to clean this shit',
        members: 20,
        donation: 2000,
    },
    {
        name: 'Beach',
        image: '',
        Location: 'LA',
        description: 'Beach has been polluted by plastic. Come forward to clean this shit',
        members: 20,
        donation: 2000,
    },
    {
        name: 'Beach',
        image: '',
        Location: 'LA',
        description: 'Beach has been polluted by plastic. Come forward to clean this shit',
        members: 20,
        donation: 2000,
    },
    {
        name: 'Beach',
        image: '',
        Location: 'LA',
        description: 'Beach has been polluted by plastic. Come forward to clean this shit',
        members: 20,
        donation: 2000,
    },
    {
        name: 'Beach',
        image: '',
        Location: 'LA',
        description: 'Beach has been polluted by plastic. Come forward to clean this shit',
        members: 20,
        donation: 2000,
    },
    {
        name: 'Beach',
        image: '',
        Location: 'LA',
        description: 'Beach has been polluted by plastic. Come forward to clean this shit',
        members: 20,
        donation: 2000,
    },
    {
        name: 'Beach',
        image: '',
        Location: 'LA',
        description: 'Beach has been polluted by plastic. Come forward to clean this shit',
        members: 20,
        donation: 2000,
    },
]