import img1 from '../Assets/Img1.jpg'

export const campaigns = [
    {
        name: 'Beach',
        image: img1,
        Location: 'LA',
        description: 'Beach has been polluted by plastic. Come forward to clean this shit',
        members: 20,
        donation: 2000,
    },
    {
        name: 'Beach',
        image: img1,
        Location: 'LA',
        description: 'Beach has been polluted by plastic. Come forward to clean this shit',
        members: 20,
        donation: 2000,
    },
    {
        name: 'Beach',
        image: img1,
        Location: 'LA',
        description: 'Beach has been polluted by plastic. Come forward to clean this shit',
        members: 20,
        donation: 2000,
    },
    {
        name: 'Beach',
        image: img1,
        Location: 'LA',
        description: 'Beach has been polluted by plastic. Come forward to clean this shit',
        members: 20,
        donation: 2000,
    },
    {
        name: 'Beach',
        image: img1,
        Location: 'LA',
        description: 'Beach has been polluted by plastic. Come forward to clean this shit',
        members: 20,
        donation: 2000,
    },
    {
        name: 'Beach',
        image: img1,
        Location: 'LA',
        description: 'Beach has been polluted by plastic. Come forward to clean this shit',
        members: 20,
        donation: 2000,
    },
    {
        name: 'Beach',
        image: img1,
        Location: 'LA',
        description: 'Beach has been polluted by plastic. Come forward to clean this shit',
        members: 20,
        donation: 2000,
    },
    {
        name: 'Beach',
        image: img1,
        Location: 'LA',
        description: 'Beach has been polluted by plastic. Come forward to clean this shit',
        members: 20,
        donation: 2000,
    },
    {
        name: 'Beach',
        image: img1,
        Location: 'LA',
        description: 'Beach has been polluted by plastic. Come forward to clean this shit',
        members: 20,
        donation: 2000,
    },
    {
        name: 'Beach',
        image: img1,
        Location: 'LA',
        description: 'Beach has been polluted by plastic. Come forward to clean this shit',
        members: 20,
        donation: 2000,
    },
    {
        name: 'Beach',
        image: img1,
        Location: 'LA',
        description: 'Beach has been polluted by plastic. Come forward to clean this shit',
        members: 20,
        donation: 2000,
    },
    {
        name: 'Beach',
        image: img1,
        Location: 'LA',
        description: 'Beach has been polluted by plastic. Come forward to clean this shit',
        members: 20,
        donation: 2000,
    },
]